Update metadata
mdx-js/vscode-mdx pull request #214
Opened 2022-08-06 13:08 UTC by remcohaszing

Mentioning _VSCode_ in the display name and description is redundant, as it’s used for representing the extension inside VSCode (or even an alternative compatible editor that isn’t VSCode).

The `qna` link is linked from https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx&ssr=false#qna. By default it appears to link the repository issue tracker.

The sponsor url is rendered in VSCode. For example:

![remark extension page in VSCode](https://user-images.githubusercontent.com/779047/183250079-063d3475-0a5d-466c-a3da-e98ba8a3d8e4.png 'remark extension page in VSCode')

The `funding` field is for npm packages and is actually meaningless for VSCode extensions. I don’t know what the `donate` field is used for, but it seems redundant too.

2022-08-06 13:14 UTC, ChristianMurphy approved these changes

2022-08-18 01:11 UTC, JounQin requested changes

2022-08-18 01:11 UTC, JounQin commented on package.json
> +  "displayName": "MDX",
I love these changes!

2022-08-18 04:50 UTC, merged

2022-08-18 04:51 UTC, JounQin commented
Thanks @remcohaszing

2022-08-18 04:56 UTC, JounQin commented
@ChristianMurphy Can you help to change the description link here?

<img width="438" alt="image" src="https://user-images.githubusercontent.com/8336744/185297117-1712919e-6328-453d-86d8-27f4f88a8bad.png">