feat Support for highlighting JSX evaluated expressions
mdx-js/vscode-mdx pull request #222
Opened 2022-08-27 02:18 UTC by KeyboardSounds

In JSX, you can include JS expressions within tags, like:
```
<ATag>
{doSomething(‘a’, 7)}
</asdfadf
```

This PR adds syntax highlighting for those expressions.

### Limitations
It will still highlight JS that isn’t valid to include in a JSX evaluated expression (eg. a class definition), which as far as I can tell is a limitation of how embedded languages work in TextMate syntax highlighting definitions.

2022-08-27 02:20 UTC, KeyboardSounds commented
In its current state, this PR fails linting:

```
yarn run v1.22.15
$ /workspaces/vscode-mdx-1/node_modules/.bin/lint-staged
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ .lintstagedrc.js — 2 files
    ↓ *.{*sh,env,env.*,gql,ini,properties,rb,css,less,sass,scss,styl,stylus,svelte,vue} — no files [SKIPPED]
    ↓ .!(browserslistrc|nvm)rc — no files [SKIPPED]
    ↓ Dockerfile — no files [SKIPPED]
    ❯ *.{cjs,cts,js,json,jsonc,json5,jsx,html,md,mdx,mjs,mts,pug,svelte,toml,ts,tsx,vue,yaml,yml} — 2 files
      ✖ eslint --cache -f friendly --fix [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --cache -f friendly --fix:


  ✘  http://eslint.org/docs/rules/

     Parsing error: Could not parse expression with acorn: Expecting Unicode escape sequence \uXXXX


     test/fixture.mdx:28:5
     26 | Lorem ipsum dolor sit _amet_, consectetur adipiscing elit. Ut ac lobortis velit.
     27 | 
   > 28 | {3 \* 7}
        |     ^
     29 | 

✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I could change the text case to avoid this, but that seems dodgy. Does anyone have any pointers on how to fix this? I’m a bit lost on how the linting config works for this repo.

2022-12-15 14:27 UTC, remcohaszing requested changes
Thank you for your contribution!

It looks like CI failed due to a bug in `eslint-mdx`. Since the ESLint check has been removed, this should no longer be an issue.

Your changes look great! Could you rebase?

2022-12-15 14:27 UTC, remcohaszing commented on .changeset/short-coins-bow.md
> +It will still highlight JS that isn’t valid to include in a JSX evaluated expression (eg. a class definition), which as far as I can tell is a limitation of how embedded languages work in TextMate sy
It’s totally valid to include a class declaration in a JSX expression!

Some things are invalid though, e.g. ESM. I don’t think that’s a limitation though. The ability to provide syntax highlighting for invalid code is a feature, not a bug or limitation. Invalid syntax will be reported by the intellisense introduced in #226.

```suggestion
```

2022-12-15 14:27 UTC, remcohaszing commented on syntaxes/mdx.tmLanguage.json
> +      },
```suggestion
    },
```

2022-12-22 09:27 UTC, remcohaszing approved these changes

2022-12-22 09:29 UTC, merged

2023-01-13 15:10 UTC, remcohaszing commented
Your changes have been released in version [1.1.0](https://github.com/mdx-js/vscode-mdx/releases/tag/v1.1.0). Thanks again! :heart: